#!/bin/sh
# ---------------------------------------------------------------------------
# Generate a build-filesystem package that installs every userland executable
# actually built by the `bin` target into /bin, so the root filesystem is
# populated with exactly the programs that were compiled (no static package
# referencing binaries this curated tree does not build).
#
#   gen-binpkg.sh <userland-bin-dir> <output.pkg> [package-name]
#
# Each bare executable <name> (files without a .map/.rel/.o/.sym extension)
# becomes:  f 0755 /bin/<name>  <name>
# The source is a plain basename; build-filesystem resolves it via its --search
# roots (which include the userland/bin dir). /init is skipped: basefs installs
# it as /init already.
# ---------------------------------------------------------------------------
set -e

BINDIR="$1"
OUT="$2"
PKG="${3:-genbin}"

{
    echo "# Auto-generated by gen-binpkg.sh - do not edit."
    echo "package $PKG"
    echo
    for f in "$BINDIR"/*; do
        [ -f "$f" ] || continue
        name=$(basename "$f")
        case "$name" in
            *.map|*.rel|*.o|*.sym|*.lst|*.ihx|*.bin|*.noi) continue ;;
            init) continue ;;   # installed as /init by basefs
        esac
        printf 'f 0755 /bin/%s\t%s\n' "$name" "$name"
    done
} > "$OUT"

echo "gen-binpkg: wrote $OUT ($(grep -c '^f ' "$OUT") programs from $BINDIR)"
