/*
 *	Generate the syscall functions
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include "syscall_name.h"

static char namebuf[128];

static void write_call(int n)
{
  FILE *fp;
  snprintf(namebuf, 128, "fuzix6502/syscall_%s.s", syscall_name[n]);
  fp = fopen(namebuf, "w");
  if (fp == NULL) {
    perror(namebuf);
    exit(1);
  }
  fprintf(fp, "\t.code\n");
  fprintf(fp, "\t.export _%s\n\n", syscall_name[n]);
  fprintf(fp, "\t_%s:\n", syscall_name[n]);
  fprintf(fp, "\tldx #%u\n", n);
  fprintf(fp, "\tjsr __syscall\n");
  if (syscall_args[n] != VARARGS) {
    /* Clean stack */
    fprintf(fp, "\tldy #%u\n", 2 * syscall_args[n]);
    fprintf(fp, "\tjmp __addysp\n");
  } else {
    /* Varargs - caller cleans */
    fprintf(fp, "\trts\n");
  }
  fclose(fp);
}

static void write_call_table(void)
{
  int i;
  for (i = 0; i < NR_SYSCALL; i++)
    write_call(i);
}

static void write_makefile(void)
{
  int i;
  FILE *fp;

  mkdir("fuzix6800", 0777);

  fp = fopen("fuzix6502/Makefile", "w");
  if (fp == NULL) {
    perror("Makefile");
    exit(1);
  }
  fprintf(fp, "# Autogenerated by tools/syscall6502\n");
  fprintf(fp, "ASRCS = syscall_%s.s\n", syscall_name[0]);
  for (i = 1; i < NR_SYSCALL; i++)
    fprintf(fp, "ASRCS += syscall_%s.s\n", syscall_name[i]);
  fprintf(fp, "\n\nASRCALL = $(ASRCS)\n");
  fprintf(fp, "\nAOBJS = $(ASRCALL:.s=.o)\n\n");
  fprintf(fp, "../syslib.lib: $(AOBJS) syscall.o\n");
  fprintf(fp, "\techo $(AOBJS) syscall.o >syslib.l\n");
  fprintf(fp, "\tar rc ../syslib.lib $(AOBJS) syscall.o\n\n");
  fprintf(fp, "$(AOBJS): %%.o: %%.s\n");
  fprintf(fp, "\tfcc -m6502 -c -o $*.o $<\n\n");
  fprintf(fp, "syscall.o: syscall.s\n");
  fprintf(fp, "\tfcc -m6502 -c -o $*.o $<\n\n");
  fprintf(fp, "clean:\n");
  fprintf(fp, "\trm -f $(AOBJS) $(ASRCS) syscall.o *~\n\n");
  fclose(fp);
}

int main(int argc, char *argv[])
{
  write_makefile();
  write_call_table();
  exit(0);
}
