# ---------------------------------------------------------------------------
# Platform: rpipico (Raspberry Pi Pico / RP2040, ARM Cortex-M0+)  CPU: armm0
#
# Transcribes platform-rpipico/CMakeLists.txt (the upstream Pico-SDK project)
# into our tree: same compile definitions, include dirs, source list, linked
# SDK libraries and pico_add_extra_outputs(), but driven from OUR top-level
# CMake and reading sources from the fuzix-new kernel/ layout.
#
# Prerequisites are set up by the early Pico hook in the top-level CMakeLists
# (pico_sdk_import.cmake before project(), C/CXX/ASM enabled, pico_sdk_init()).
# The top-level returns right after including this file, so none of the fcc/gcc
# link / diskimage / userland machinery runs for this board.
#
# Build:
#   cmake -B build -DFUZIX_CPU=armm0 -DFUZIX_PLATFORM=rpipico \
#         [-DPICO_BOARD=pico|pico2] [-DPICO_SDK_PATH=... -DPICO_TOOLCHAIN_PATH=...]
#   cmake --build build            # -> build/fuzix.elf + build/fuzix.uf2
# ---------------------------------------------------------------------------

# TOTALMEM depends on the SDK board (RP2040 = 160, RP2350/pico2 = 320).
if(PICO_BOARD MATCHES "pico2")
    set(TOTALMEM 320)
else()
    set(TOTALMEM 160)
endif()

set(PICO_COPY_TO_RAM 1)

add_compile_definitions(
    PICO_HEAP_SIZE=0x0
    PICO_NO_BINARY_INFO=1
    PICO_TIME_DEFAULT_ALARM_POOL_DISABLED
    TOTALMEM=${TOTALMEM})

# Upstream: . ../.. ../../dev ../../dev/net ../../include ../../cpu-armm0
# fuzix-new layout: platform dir + kernel/{core,include,dev,dev/net,cpu/armm0}.
include_directories(
    ${KDIR}/platform/rpipico
    ${KDIR}/core
    ${KDIR}
    ${KDIR}/dev
    ${KDIR}/dev/net
    ${KDIR}/include
    ${KDIR}/cpu/armm0
    ${GEN}/include)               # generated sysinfoblk.h

# version.c + sysinfoblk.h are generated by makeversion (custom command in the
# top-level file). Make the executable wait for them before any object compiles.
set_source_files_properties("${GEN}/version.c" PROPERTIES GENERATED TRUE)
add_custom_target(fuzix_genhdr DEPENDS "${GEN}/version.c" "${GEN}/include/sysinfoblk.h")

add_executable(fuzix
    # --- platform (kernel/platform/rpipico) ---
    ${KDIR}/platform/rpipico/devices.c
    ${KDIR}/platform/rpipico/devflash.c
    ${KDIR}/platform/rpipico/devsdspi.c
    ${KDIR}/platform/rpipico/devtty.c
    ${KDIR}/platform/rpipico/elf.c
    ${KDIR}/platform/rpipico/main.c
    ${KDIR}/platform/rpipico/misc.c
    ${KDIR}/platform/rpipico/rawflash.c
    ${KDIR}/platform/rpipico/rawuart.c
    ${KDIR}/platform/rpipico/swapper.c
    ${KDIR}/platform/rpipico/tricks.S
    ${KDIR}/platform/rpipico/core1.c
    ${KDIR}/platform/rpipico/devgpio.c
    ${KDIR}/platform/rpipico/usbdescriptors.c
    ${KDIR}/platform/rpipico/wiznet.c
    ${KDIR}/platform/rpipico/wiznet_spi.c
    # --- shared drivers ---
    ${KDIR}/dev/blkdev.c
    ${KDIR}/dev/mbr.c
    ${KDIR}/dev/devsd_discard.c
    ${KDIR}/dev/devsd.c
    ${KDIR}/dev/net/net_native.c
    ${KDIR}/dev/net/net_w5x00.c
    # --- Dhara flash translation layer + hexdump ---
    ${KDIR}/lib/dhara/error.c
    ${KDIR}/lib/dhara/journal.c
    ${KDIR}/lib/dhara/map.c
    ${KDIR}/lib/hexdump.c
    # --- portable core ---
    ${KDIR}/core/blk512.c
    ${KDIR}/core/devio.c
    ${KDIR}/core/devsys.c
    ${KDIR}/core/filesys.c
    ${KDIR}/core/inode.c
    ${KDIR}/core/kdata.c
    ${KDIR}/core/mm.c
    ${KDIR}/core/process.c
    ${KDIR}/core/start.c
    ${KDIR}/core/swap.c
    ${KDIR}/core/syscall_execelf32.c
    ${KDIR}/core/syscall_exec.c
    ${KDIR}/core/syscall_fs.c
    ${KDIR}/core/syscall_fs2.c
    ${KDIR}/core/syscall_fs3.c
    ${KDIR}/core/syscall_other.c
    ${KDIR}/core/syscall_proc.c
    ${KDIR}/core/syscall_net.c
    ${KDIR}/core/network.c
    ${KDIR}/core/timer.c
    ${KDIR}/core/tty.c
    ${KDIR}/core/usermem.c
    ${GEN}/version.c
    # --- cpu + mm (core/mm.c already listed above) ---
    ${KDIR}/cpu/armm0/lowlevel-armm0.c
    ${KDIR}/mm/malloc.c
    ${KDIR}/mm/memalloc_none.c)

target_link_libraries(fuzix
    pico_stdlib
    pico_multicore
    hardware_flash
    hardware_spi
    tinyusb_device)

add_dependencies(fuzix fuzix_genhdr)

pico_set_float_implementation(fuzix none)
pico_set_double_implementation(fuzix none)
pico_add_extra_outputs(fuzix)
