# ===========================================================================
# programs.cmake - FUZIX userland program registry (data for UserBin.cmake).
#
# One fuzix_program() per program. Packages group them for the FUZIX_PKG_*
# switches; PROGRAMS.md is the human-readable mirror. Generated from
# Applications/util/Makefile.common + V7/cmd/sh; grow deliberately.
#   coreutils        - curated default-on core set
#   coreutils-extra  - the rest of util/ (opt-in)
#   editors          - termcap-based editors/pagers from util/ (opt-in)
#   shell            - the V7 Bourne shell
# ===========================================================================

# --- coreutils (curated, default ON) ---
fuzix_program(NAME basename     PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME cat          PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME chmod        PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME cmp          PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME date         PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME dirname      PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME false        PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME head         PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME kill         PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME mkdir        PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME pwd          PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME rm           PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME rmdir        PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME sync         PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME touch        PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME true         PACKAGE coreutils        CRT0 nostdio)
fuzix_program(NAME cksum        PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME cp           PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME cut          PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME df           PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME echo         PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME env          PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME grep         PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME ls           PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME more         PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME mount        PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME sleep        PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME sort         PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME umount       PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME uname        PACKAGE coreutils        CRT0 stdio)
fuzix_program(NAME wc           PACKAGE coreutils        CRT0 stdio)

# --- coreutils-extra (rest of util/, default OFF) ---
fuzix_program(NAME border       PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME chgrp        PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME chown        PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME groups       PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME init         PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME killall      PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME logname      PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME mkfifo       PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME mknod        PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME pagesize     PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME printenv     PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME prtroot      PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME reboot       PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME substroot    PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME sum          PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME tee          PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME telinit      PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME tr           PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME while1       PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME whoami       PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME yes          PACKAGE coreutils-extra  CRT0 nostdio)
fuzix_program(NAME banner       PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME bd           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME blkdiscard   PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME cal          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME chmem        PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME cu           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME dd           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME decomp16     PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME dosread      PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME du           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME ed           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME factor       PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME fdisk        PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME fgrep        PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME free         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME fsck         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME fsck-fuzix   PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME gpiotool     PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME gptparse     PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME id           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME kbdrate      PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME labelfs      PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME ll           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME mail         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME man          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME manscan      PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME mkfs         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME mode         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME nvtool       PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME od           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME passwd       PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME ps           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME remount      PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME rx           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME sed          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME seq          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME setboot      PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME setdate      PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME size         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME ssh          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME socktest     PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME stty         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME su           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME swapon       PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME sx           PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME tar          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME tail         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME termcap      PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME uniq         PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME uptime       PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME uud          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME uue          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME which        PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME who          PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME write        PACKAGE coreutils-extra  CRT0 stdio)
fuzix_program(NAME xargs        PACKAGE coreutils-extra  CRT0 stdio)

# --- editors (termcap; default OFF) ---
fuzix_program(NAME fleamacs     PACKAGE editors          CRT0 stdio LIBS termcap)
fuzix_program(NAME less         PACKAGE editors          CRT0 stdio LIBS termcap)
fuzix_program(NAME tget         PACKAGE editors          CRT0 stdio LIBS termcap)
fuzix_program(NAME tchelp       PACKAGE editors          CRT0 stdio LIBS termcap)
fuzix_program(NAME marksman     PACKAGE editors          CRT0 stdio LIBS termcap)
fuzix_program(NAME vile         PACKAGE editors          CRT0 stdio LIBS termcap)

# --- shell ---
fuzix_program(NAME sh PACKAGE shell CRT0 stdio DIR sh
    SOURCES args.c blok.c builtin.c cmd.c ctype.c error.c expand.c fault.c io.c
            macro.c main.c msg.c name.c print.c service.c setbrk.c stak.c string.c
            word.c xec.c glob.c)
